Algoritmo "mediaIdades"

Var
 a, b : caractere
 i1, i2 : inteiro
 m : real
 
Inicio

escreval("Dados da primeira pessoa: ")
escreva("Nome: ")
leia(a)
escreva("Idade: ")
leia(i1)
escreval("Dados da segunda pessoa: ")
escreva("Nome: ")
leia(b)
escreva("Idade: ")
leia(i2)

m <- (i1 + i2) /2

escreval("A idade media de Maria Silva e Joao Melo eh de", m," anos")



Fimalgoritmo