Algoritmo "test_saida"

Var

 codigo: inteiro
 idade: inteiro
 preco1: real
 preco2: real
 produto1: caractere
 produto2: caractere
 genero: caractere

Inicio

produto1 <- "Computador"
produto2 <- "TV"
preco1 <- 2100.5
preco2 <- 1830
idade <- 30
codigo <- 5291
genero <- "F"


escreval("Produtos:")
escreval("O ", produto1," custa"," R$", preco1:8:2)
escreval("A ", produto2," custa"," R$", preco2:8:2)
escreval
escreval("Codigo =", codigo)
escreval
escreval("Dados do cliente: ","genero ", genero," e idade", idade," anos")



Fimalgoritmo